parameters:
  name: ''
  pool: {}
  strategy: {}
  skipTests: true
  targetOS: ''
  timeoutInMinutes: 120
  testOuterloop: false
  container: ''
  buildScriptPrefix: ''
  submitToHelix: true
  displayName: ''
  useCustomBuildSteps: false
  customBuildSteps: []
  preBuildSteps: []

jobs:
  - job: ${{ parameters.name }}
    variables:
      # OS Specific commands
      ${{ if eq(parameters.targetOS, 'Windows_NT') }}:
        _buildScript: build.cmd -ci
        _msbuildCommand: powershell -ExecutionPolicy ByPass -NoProfile eng\common\msbuild.ps1 -warnaserror:0 -ci
      ${{ if ne(parameters.targetOS, 'Windows_NT') }}:
        _buildScript: ${{ parameters.buildScriptPrefix }}./build.sh --ci
        _msbuildCommand: ${{ parameters.buildScriptPrefix }}./eng/common/msbuild.sh --warnaserror false --ci

    displayName: ${{ parameters.displayName }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    pool:
      ${{ insert }}: ${{ parameters.pool }}
    
    ${{ if ne(parameters.strategy, '') }}:
      strategy:
        maxParallel: 99
        ${{ insert }}: ${{ parameters.strategy }}

    container: ${{ parameters.container }}

    steps:
      - ${{ parameters.preBuildSteps }}

      - ${{ if eq(parameters.useCustomBuildSteps, 'false') }}:
        - script: $(_buildScript)
                -includetests
                -framework $(framework)
                /p:ArchGroup=$(_archGroup)
                /p:ConfigurationGroup=$(_configuration)
                /p:SkipTests=${{ parameters.skipTests }}
                /p:ArchiveTests=${{ parameters.submitToHelix }}
                /p:Outerloop=${{ parameters.testOuterloop }}
                ${{ parameters.buildExtraArguments }}
          displayName: Build Sources and Tests
    
      - ${{ if eq(parameters.useCustomBuildSteps, 'true') }}:
        - ${{ parameters.customBuildSteps }}

      - ${{ if eq(parameters.submitToHelix, 'true') }}:
        - template: /eng/pipelines/helix.yml
          parameters:
            targetOS: ${{ parameters.targetOS }}
            archGroup: $(_archGroup)
            configuration: $(_configuration)
            helixQueues: $(helixQueues)
            msbuildScript: $(_msbuildCommand)
            framework: $(framework)
