# Linux legs
jobs:

# Legs with Helix testing
- template: /eng/pipelines/corefx-base.yml
    parameters:
      name: LinHelix
      displayName: Linux
      strategy:
        matrix:
          # netcoreapp linux x64 release
          x64_Release:
            _configuration: Release
            _archGroup: x64
            framework: netcoreapp
            helixQueues: $(_linuxDefaultQueues)
            _dockerContainer: RhelContainer

      pool:
        name: Hosted Ubuntu 1604

      targetOS: Linux
      container: $[ variables['_dockerContainer'] ]

# Legs without helix
# - template: /eng/pipelines/corefx-base.yml
#     parameters:
#       name: LinNoHelix
#       displayName: Linux
#       strategy:
#         matrix:
#           # linux-musl x64 debug
#           musl_x64_Debug:
#             _configuration: Debug
#             _archGroup: x64
#             framework: netcoreapp
#             _dockerContainer: AlpineContainer
#             _buildExtraArguments: /p:RuntimeOs=linux-musl /p:PortableBuild=false
#       pool:
#         name: Default

#       targetOS: Linux
#       container: $[ variables['_dockerContainer'] ]
#       buildExtraArguments: $(_buildExtraArguments)
#       submitToHelix: false
